name: popup_shape
description: Custom Popup Shapes
version: 0.0.1
homepage: https://github.com/MR0100/popup_shapes.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  
  assets:
    - assets/
    - assets/images/
 